version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    # ports:
    #  - 5432:5432
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      - db
    ports:
      - 5050:5050
    volumes:
      - ./postgres/servers.json:/pgadmin4/servers.json
    env_file:
      - .env

  dbt:
    build: 
      context: .
      dockerfile: dbt-bicycle-sharing/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./dbt-bicycle-sharing:/dbt
      - my-profile:/dbt/profile
      - my-target:/dbt/target
    entrypoint: /bin/bash
    command: -c "dbt deps && dbt run && dbt docs generate"
    restart: "no"

  dbt_doc:
    image: flashspys/nginx-static
    depends_on:
      - dbt
    ports:
      - 8082:80
    volumes:
      - my-target:/static

volumes:
  app-db-data:
  my-profile:
  my-target:

